"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 01:08:48.950480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('tipo_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('etnia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persona_vulnerable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_numero_identificacion'), 'usuario', ['numero_identificacion'], unique=False)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radicado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_solicitud', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asunto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_responsable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persona_vulnerable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_radicacion', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('fecha_limite', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('fecha_respuesta', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_area_responsable'), 'solicitud', ['area_responsable'], unique=False)
    op.create_index(op.f('ix_solicitud_estado'), 'solicitud', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitud_radicado'), 'solicitud', ['radicado'], unique=True)
    op.create_index(op.f('ix_solicitud_tipo_solicitud'), 'solicitud', ['tipo_solicitud'], unique=False)
    op.create_index(op.f('ix_solicitud_usuario_id'), 'solicitud', ['usuario_id'], unique=False)
    op.create_table('adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ruta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('es_respuesta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjunto_solicitud_id'), 'adjunto', ['solicitud_id'], unique=False)
    op.create_table('estado_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_cambio', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_cambio_solicitud_id'), 'estado_cambio', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estado_cambio_solicitud_id'), table_name='estado_cambio')
    op.drop_table('estado_cambio')
    op.drop_index(op.f('ix_adjunto_solicitud_id'), table_name='adjunto')
    op.drop_table('adjunto')
    op.drop_index(op.f('ix_solicitud_usuario_id'), table_name='solicitud')
    op.drop_index(op.f('ix_solicitud_tipo_solicitud'), table_name='solicitud')
    op.drop_index(op.f('ix_solicitud_radicado'), table_name='solicitud')
    op.drop_index(op.f('ix_solicitud_estado'), table_name='solicitud')
    op.drop_index(op.f('ix_solicitud_area_responsable'), table_name='solicitud')
    op.drop_table('solicitud')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_numero_identificacion'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
